<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'BetterMessages\\React\\Stream\\' => array($vendorDir . '/react/stream/src'),
    'BetterMessages\\React\\Socket\\' => array($vendorDir . '/react/socket/src'),
    'BetterMessages\\React\\Promise\\' => array($vendorDir . '/react/promise/src'),
    'BetterMessages\\React\\Http\\' => array($vendorDir . '/react/http/src'),
    'BetterMessages\\React\\EventLoop\\' => array($vendorDir . '/react/event-loop/src'),
    'BetterMessages\\React\\Dns\\' => array($vendorDir . '/react/dns/src'),
    'BetterMessages\\React\\Cache\\' => array($vendorDir . '/react/cache/src'),
    'BetterMessages\\Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'BetterMessages\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'BetterMessages\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'BetterMessages\\Nyholm\\Psr7\\' => array($vendorDir . '/nyholm/psr7/src'),
    'BetterMessages\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'BetterMessages\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'BetterMessages\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'BetterMessages\\Fig\\Http\\Message\\' => array($vendorDir . '/fig/http-message-util/src'),
    'BetterMessages\\Evenement\\' => array($vendorDir . '/evenement/evenement/src'),
);
