<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'c52340349845674640f31d959b6f1873' => $vendorDir . '/react/promise/src/functions_include.php',
    'b62dcd520cbfb66b4b79b743ca125850' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    'fd4da2feb0c35ca29f7a4284d1bcfc4d' => $vendorDir . '/symfony/deprecation-contracts/function.php',
    '19be85b8c021d4d805db2cfd50f1f602' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
);
